/**
!!! AUTOMATICALLY GENERATED by the esp-quick-toolchain build script !!!
*/

#pragma once

#define __EQT_EXCSTR_CONCAT_IMPL(X, Y, Z) X ## Y ## Z
#define __EQT_EXCSTR_CONCAT(X, Y, Z) __EQT_EXCSTR_CONCAT_IMPL(X, Y, Z)
#define __EQT_EXCSTR_ATTR __attribute__((section(".irom.exceptiontext"))) __attribute__((aligned(4)))

#if (__cplusplus >= 201103L)
#define __EQT_EXCSTR_CONSTEXPR constexpr
#else
#define __EQT_EXCSTR_CONSTEXPR
#endif

#define __EQT_EXCSTR_DECL(NAME, s)\
    static __EQT_EXCSTR_CONSTEXPR const char NAME [] __EQT_EXCSTR_ATTR = s

#define __EQT_EXCSTR_WRAP(NAME, s) (({ __EQT_EXCSTR_DECL(NAME, s); &NAME[0]; }))
#define __EQT_EXCSTR_NAME(X) __EQT_EXCSTR_CONCAT(X, __LINE__, __COUNTER__)

#define __EQT_EXCSTR(s)\
    __EQT_EXCSTR_WRAP(__EQT_EXCSTR_NAME(__exception_what__), s)
